GET  http://localhost:3000/subscribers

###

GET  http://localhost:3000/subscribers/64f86552583e3631c600fe3e

###

POST http://localhost:3000/subscribers
Content-Type: application/json
{
    "name" : "Subhendu Dey",
    "subscribedToChannel" : "NrXen Dev"
}