GET  http://localhost:3000/subscribers

###

GET  http://localhost:3000/subscribers/1069

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{   "roll" : "1069",
    "name" : "Mainak Majumder",
    "stream" : "ECE",
    "year" : "2019"
}

###

DELETE   http://localhost:3000/subscribers/1034